---
title: "事故因果模型"
editor: visual
---

事故是複雜的，理解事故發生的方式一直都是一個具有挑戰性的問題，自1930 年代以來，關於事故因果的思維經歷了一個演變過程，從簡單的「骨牌模型」發展到系統模型，再到更新近的複雜非線性模型。儘管模型有各自成立背景、條件與複雜性，但對於職安衛人員而言，理解事故因果模式(Accident Cause-Effect Models)有助於建立有效的系統性事故預防方法，並能夠有效地應對已發生事故的分析。本章節盡可能收集文獻資料，整理事故因果模式並進行簡介，職安衛人員可參酌相關文獻或指引，就有興趣之模式深入鑽研，相信對自身職安衛專業能力提升會有助益。 為何要了解事故因果模式呢？確定事故發生的「原因」是事故調查的關鍵目標，而調查小組(或人員)事故因果的心智模式對於事故調查至關重要，因為1.事故因果模式提供理解事故現象的框架，建立對事故如何發生的共同理解，從而更好地分析事故。2.指導調查方向和資料收集，不同的事故模型指導調查人員應該尋找哪些資訊以及如何收集這些資訊，如果調查人員採用線性模型，他們可能會更關注事件的順序，而系統模型則會引導調查人員關注組織因素和潛在條件，美國能源部(DOE)也指出借助理論的因果模型來制定進一步調查的問題[@doe2012a]。3.協助分析因素之間的相互關係，事故通常是多個因素相互作用的結果，事故因果模型有助於調查人員理解這些因素之間是如何相互關聯並最終導致事故發生的。例如，”Swiss Cheese Model” 乳酪模型強調多個防禦層中的「漏洞」如何對齊導致事故[@pryorp.2012]。4.影響對「根本原因」的認定，因為未找出真正「根本原因」，可能只會消除表面症狀，調查中發現的原因會被視為需要修復的特定問題，不同的模型可以提供不同的思維模式，激發更深入的分析，從而識別更根本的系統性原因[@lundberg2009]。5.有助於減少個人偏見，模型為事故起因提供了一個共同的基礎，從而減少了關於事故起因的個人偏見，並為更廣泛的預防措施開啟思路。所以，事故因果模式不僅為理解事故的複雜性提供了理論基礎，更在實務中指引事故調查的整個過程，從問題的提出、資料的收集與分析，到最終根本原因的確定和預防措施的制定，與調查報告溝通討論等。選擇合適的事故因果模式有助於調查人員更全面、深入地理解事故的本質，從而制定更有效的預防策略，避免類似事故的再次發生。 事故因果模式依時間軸發展，可以概分為三大模型：

### (一). 簡單線性系統模式 (Simple Linear System Models)

早期的事故模型著重於操作員與機器之間的互動，將人機環境與事故視為直接的因果關係。韓立奇的骨牌模型 (Heinrich's Domino Model) 是此類模型的代表，它認為事故是一連串線性的因果鏈，如同骨牌一樣，一個環節的失效會導致後續環節的連鎖反應，最終導致事故發生；這個模型強調移除中間的一個“骨牌”（原因）就可以阻止事故的發生[@doe2012b; @oakley2003; @pryorp.2012]。我國職安署重大職災原因分析中的間接原因，包含不安全動作(unsafe acts)與不安全狀況(unsafe mechanical or physical conditions)[@mol-osha2021]，這原因歸類可推論由此簡單線性模式所衍生。

### (二). 複雜線性模型 (Complex Linear Models)

此模型考量到在事故發生前可能存在許多未被注意到的因果鏈，最廣為人知的複雜線性事故模型是乳酪模型 (Reason’s Swiss Cheese Model)。此模型將系統的防禦措施比喻為多層次的瑞士乳酪，乳酪上的孔洞代表系統中個別部分的弱點，這些孔洞的大小和位置會不斷變化。當所有層次的孔洞在某一時刻對齊時，就會形成“發生事故機會的軌跡”，使得潛在的危害得以穿過所有防禦，最終導致事故發生。乳酪模型認為事故是由主動失效 (active failures) (不安全行為)和潛在條件(latent conditions) (系統中預先存在的缺陷)的線性組合所造成，這也將事故調查的重點從責怪個人轉向系統分析，關注潛在的危害、防禦和損失[@pryorp.2012]。

### (三). 複雜非線性模型/系統模型 (Complex Non-linear Models / Systemic Model)

複雜非線性模型簡稱系統性模型，是近期發展的事故因果模式，主要用於理解在高度複雜的系統中，例如核電廠等，事故是如何發生的。這些模型與早期的線性模型有顯著的不同，它們不再將事故視為單一的因果鏈或一系列的故障累積，而是強調多個因素在系統內相互作用和影響，最終導致事故的發生。霍納格爾 (Hollnagel) 的功能共振事故模型 (Functional Resonance Accident Model, FRAM) 是一種代表模型，它將事故視為相互依存的功能之間產生的意外行為，這些功能的表現取決於其他功能和不同的因素。此類模型著重於整體，從整體和相互關聯的角度來理解事故，而非個別部分，並將損失描述為系統在不受控關係下產生的意外行為。與之前的線性模型相比，複雜非線性模型的主要區別在於，事故發生是多個因素同時作用和相互影響，而不是簡單的線性序列，係系統行為互動，而不是個別部分的故障。它認為事故可能源於系統正常運作中不可避免的變異性的意外組合，而不是單純的“失敗”或“錯誤”。其預防策略不再僅僅是消除單一原因或加強線性防禦，而是需要理解和管理系統的複雜性和變異性，提升系統的韌性 (resilience)，使其能夠在面對意外情況時進行調整和恢復[@doe2012a; @lundberg2009; @pryorp.2012]。 事故調查的分析本身會受到組織與調查人員建立的底層事故因果模型的影響，而提出的建議也可能受到政治和經濟因素的考量[@lundberg2009]。總結來說，事故因果模式的發展從簡單的線性因果關係，逐步演變到考慮更複雜的系統互動和潛在因素。不同的模型提供了不同的視角來理解事故的發生機制，並影響著事故調查的重點和後續的預防措施。在進行事故調查時，選擇合適的事故模型對於理解“發生了什麼”以及“為什麼會發生”至關重要[@doe2012a]。
